### ISSUE TITLE
Add `training=False` when converting DINO weights

### ISSUE THREAD

**Issue by AntoineToubhans** [sayakpaul/probing-vits#27]
Hey @sayakpaul ,
Thanks for the notebook and the awesome work here, very helpful :)

I think there is a small typo in the ["load-dino-weights" notebook](https://github.com/sayakpaul/probing-vits/blob/main/notebooks/load-dino-weights-vitb16.ipynb):

In the "Validating the initial architecture" cell, when calling `vit_dino_base`, you should pass `training=False` argument:

```
vit_dino_base = ViTDINOBase(config)

dummy_inputs = tf.random.normal((2, 224, 224, 3))
outputs, attn_scores = vit_dino_base(dummy_inputs, training=False)  # I added the training=False args
```

Otherwise everything works fine :) 
Let me know if you want me to open a PR to fix this minor issue.
Cheers,
Antoine

**Comment by sayakpaul** [comment]
Thanks. 

It's just for validation purposes. 

Could you explain the significance behind passing the argument given that the results (`output`, `attn_scores`) aren't being used anywhere.

**Comment by AntoineToubhans** [comment]
Yes actually I don't need the `attn_scores`. Just for validation purposes as you said.

I added the `training=False` argument because otherwise `vit_dino_base(dummy_inputs)` does not work as the `call` function of `ViTDINOBase` requires the `training` argument.

I think the best option would be to make the training argument optional as in `ViTClassifier` [here](https://github.com/sayakpaul/deit-tf/blob/79cc91d3cb497f7abe5111fb536968fb9d9a754d/vit/vit_models.py#L173)

**Comment by sayakpaul** [comment]
Sure. Feel free to send a PR. Thanks!

**Comment by AntoineToubhans** [comment]
👍 
The PR is here: https://github.com/sayakpaul/probing-vits/pull/28
