### ISSUE TITLE
Dino Base models in saved model format 

### ISSUE THREAD

**Issue by keertika-11** [sayakpaul/probing-vits#29]
how can the dino base model checkpoints ( Feature Extractor) in pytorch or onnx  be converted into Saved  Model Format ( Tensorflow)? which will help in finetuning the dino model

**Comment by sayakpaul** [comment]
You could discard the classification head from `ViTDINOBase` (shown in [this notebook](https://github.com/sayakpaul/probing-vits/blob/main/notebooks/load-dino-weights-vitb16.ipynb)) and follow the rest of the process.
